name: pets
favicon: null
layout_spectrum: 0.13901298842392862
typography_spectrum: 0.7150568114593625
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.6427210690453649
  lightness: 0.8994544874876738
  saturation: 0.9800664251670241
  rhythmicContrast: 0.10212821024470031
purpose: []
